import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Import the generated API sidebar
let generatedApiSidebar: { apiSidebar?: any[] } = { apiSidebar: [] };
try {
  generatedApiSidebar = require('./docs/api/sidebars.js');
} catch {
  // First-time builds run before graphql-doc writes the generated sidebar file.
  generatedApiSidebar = { apiSidebar: [] };
}

const prefixApiDocIds = (items: any[]): any[] =>
  items.map((item) => {
    if (item?.type === 'doc' && typeof item.id === 'string' && !item.id.startsWith('api/')) {
      return { ...item, id: `api/${item.id}` };
    }

    if (item?.type === 'category' && Array.isArray(item.items)) {
      return { ...item, items: prefixApiDocIds(item.items) };
    }

    return item;
  });

const sidebars: SidebarsConfig = {
  // Tutorial sidebar - auto-generated from docs folder
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
    },
  ],

  // API sidebar - imported from generated file
  apiSidebar: prefixApiDocIds(generatedApiSidebar.apiSidebar ?? []),
};

export default sidebars;
